### ISSUE TITLE
Untested: Having a companion with you while playing Blackjack.

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#103]
Original post from a user:
"i was pushed abit by my companions, i think its because i use beast tamer and my robot companions always are pushing me/talking to me, but yeah i was pushed to the point i couldn't see the cards being played so i had to just press stay and then leave and re-enter but this might just be me with companions dismissed this didn't happen. i thought i would add it here as this seems to be pretty much the same topic rather then making a new post"

I have not done any testing on what happens if a companion is present, my theory is that with the normal vanilla 1 companion, everything is fine, however when people start modding in multiple companions like this user, then they push about. If more users report this problem I believe our policy should be only to support problems with the vanilla standard of 1 follower as trying to accomodate the nearly limitless number of followers people could have via mods is unreasonable.

**Comment by Scrivener07** [comment]
![userfeedback](https://user-images.githubusercontent.com/1912967/37244195-49442c1c-2453-11e8-89c1-05db7ac0259b.PNG)

**Comment by Scrivener07** [comment]
Can we find a solution that allows the player to have as many companions as they want?

**Comment by TheWhiteCollarPlayers** [comment]
I hope so, the problem is I am unsure how hardcoded the connection between a player and their companions is. Nor do I know how mods work around the vanilla limit, my initial idea is to flag off the X Companion is Active variable and then move the PC then when they leave flag it back on. Problem is, I am sure it isn't that simple and I can almost guarantee there will be repurcusions for that. Basically, idk.

**Comment by Scrivener07** [comment]
Expired I think knows a ton about the companion system but from what Ive gathered is the system is very inconsistent in the way it implements all the potential companions. If the problem is that companions are being teleported with the player and are bumping into you while trying to play then maybe i can find a way to suppress that. That might be preventing the companions from teleporting with the player, or disabling their AI and movement, making the player have no collision, or finding a way to avoid teleporting the player at all. I think this is worth looking it and finding a solution.

**Comment by TheWhiteCollarPlayers** [comment]
Oh actually that is a perfect solution, disabling AI will continue our games while ensuring that NPC's dont move around or do anything while playing the game

**Comment by Scrivener07** [comment]
There is the mass AI toggle in console with the command `tai.` It exists in papyrus but its a debug only function. https://www.creationkit.com/fallout4/index.php?title=EnableAI_-_Debug

We can do that in a release build with the cherry picking version https://www.creationkit.com/fallout4/index.php?title=EnableAI_-_Actor

**Comment by TheWhiteCollarPlayers** [comment]
This appears to be as simple as ticking a flag on the cell properties, testing now.

**Comment by TheWhiteCollarPlayers** [comment]
Fixed! Checked the box on the cell properties and companions will no longer travel with you to the cell!
https://github.com/Scrivener07/FO4_Games/commit/7b9cef6ec1abddc3cc2874756594d6dd60e9911e
