### ISSUE TITLE
Blackjack hole card is revealed briefly during card animation.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#106]
Its hard to notice because it happens so fast but the dealers hole card is actually revealed to the player for a moment in time.
![screenshot66](https://user-images.githubusercontent.com/1912967/37270532-99a84f82-25a5-11e8-8a41-fcbd743d9873.png)
![screenshot67](https://user-images.githubusercontent.com/1912967/37270533-9b43a7ce-25a5-11e8-80f1-8cdccabe13b2.png)
![screenshot68](https://user-images.githubusercontent.com/1912967/37270536-9c8494f4-25a5-11e8-9326-e9377f2eb0ed.png)

**Comment by TheWhiteCollarPlayers** [comment]
What's funny is that MxR covers this in his video, if I recall you have a fix for this in the works?

**Comment by Scrivener07** [comment]
I fixed it on the `motion` branch but its tied up with some other changes that are not ready yet.

**Comment by Scrivener07** [comment]
Fixed with pull request #120, closing this.
