### ISSUE TITLE
Bound presentation for the blackjack table.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#11]
As a result of the conversation on issue #5, a bound style presentation and perspective need to be created.

A top down camera view of the gambling table seems like the best choice. For now I need to explore best implementation before I know what the exact presentation may look like.

- [ ] Top down camera view of the gambling table.
- [ ] Limited input controls for the player.
- [ ] Increase card legibility by getting  the camera closer.

![capture1](https://cloud.githubusercontent.com/assets/1912967/26769119/56ba38fa-497a-11e7-871c-cb4b0027cb6d.PNG)

**Comment by TheWhiteCollarPlayers** [comment]
I believe that the top down view is best, maybe with a slight angle for immersion's sake. I would suggest using a smaller table instead of the pool table so that the camera can be brought in closer to make the cards more legible.

**Comment by Scrivener07** [comment]
The pool table is the only one with a green felt top though. I agree the camera could be pulled in closer for card legibility. The groups of cards right now are pretty close to the edge of the table. Maybe I can try grouping everything closer to the middle and pulling the whole camera in closer. The degree of tilt is tricky because I cant allow the camera to view anything outside the top of the table.

![screenshot7](https://cloud.githubusercontent.com/assets/1912967/26766313/02d6bd16-495d-11e7-8e31-f68962f7a307.png)

**Comment by TheWhiteCollarPlayers** [comment]
Good points, although I know we had discussed using other types of tables since in the wasteland people would probably just play on any flat surface they could rig up. Perhaps something like the tables found when settlement building? 
![fo4_kitchen_table_2](https://cloud.githubusercontent.com/assets/28495967/26766378/47b193cc-4956-11e7-9063-4a31240a06ed.png)

There are other options but I just came across this one first. 
Thoughts? I like the green felt background, but maybe we should wait for se7enraven to finish his

**Comment by Scrivener07** [comment]
I like the green felt too and I think Ive played card games on a pool table before. I don't plan on making the table under the cards swap to match the activated world table at this point. So, may as well make it look the best it can and the pool table is the best we have. I don't think a smaller plain table adds anything to the experience if that didn't happen to be the exact kind of table that was activated in the world.

At this point I'm trying to design it to reveal as little as possible about the gambling cells environment. Its kind of like going into a special blackjack world that looks the same no matter where you activate it from. Places like NPC dialogue, furniture, activators, holotapes, items, whatever, it all points to the same blackjack world.

**Comment by Scrivener07** [comment]
I have been struggling to find a way to get the camera closer to the gaming table. Right now the closest I can get is the height of the player where the camera sits on the player's head.

Ive thought about scaling the players height down to get the camera closer but I wanted to try one other thing first. I had the idea to create an invisible gun with a zoom. Then I can set various markers on the table as "look at" points. Then somehow invoke the gun into zooming in at a marker such as the cards in your hand.

**Comment by TheWhiteCollarPlayers** [comment]
I like the idea of your invisible gun method, that would be great to be able to use keys to look at your hand, or the dealer's hand, etc. However, at the current stage I would stick to a standard top down view as much as you can and work on making sure the card images are readable. Have you tried adjusting FOV settings? That could create a zooming effect I believe.

**Comment by Scrivener07** [comment]
I think FOV is an INI setting. Some INI settings can be changed in script so Ill have to try it before I know if that's possible but its a good lead to try.

**Comment by TheWhiteCollarPlayers** [comment]
I know that FOV can be changed via console commands so that makes me think that at the very least you could call a BAT file to change to the desired level.

**Comment by Scrivener07** [comment]
We got a lot of options to try out then. The card legibility is something I can explore deeper once objects branch gets merged to master.

**Comment by TheWhiteCollarPlayers** [comment]
Sounds good!

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as we have settled upon a fantastic presentation for the blackjack table
