### ISSUE TITLE
When npcs and companions go to sit down they go into t-pose

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#113]
**User Report**
![capture](https://user-images.githubusercontent.com/1912967/37808771-87f2c3e6-2e22-11e8-9f86-5e7e67258aed.PNG)

There is not enough information here to say if this is a real issue or not.

**Comment by TheWhiteCollarPlayers** [comment]
Needs more testing and reporting, I cannot replicate this issue and from what I can see no one else has either I will leave this open for now

**Comment by TheWhiteCollarPlayers** [comment]
Closing this, the person who reported the issue is being uncooperative, not to mention I cannot replicate the issue, this appears to be either a mod conflict or a vanilla bug, but simply put none of the research I have done indicates this is an issue with our mod.

**Comment by Scrivener07** [comment]
Agreed.
