### ISSUE TITLE
quick test of new version -0.1.2.0

### ISSUE THREAD

**Issue by SerClegane** [Scrivener07/FO4_Games#115]
used console to get deck and journal. Build a table. Lost all caps because I had 11 and choose hit.
Works fine.

**Comment by Scrivener07** [comment]
Thats great to hear everything is working fine! You must have hit more than once after your score of 11 though. Its impossible to hit once on 11 and bust (should be).

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as everything seems to be running fine for the current version, open a new issue to report....new issues.
