### ISSUE TITLE
To do: Voices for NPC's and silent file for Player Char

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#116]
I currently have all of the voice lines for the Commonwealth NPC's (those contained in BarstoolGames.esm).
I need to implement the audio files, and generate lip files for the commonwealth NPC's.
I also need to implement silent audio for the Player character.

**Comment by Scrivener07** [comment]
LFS tracking is setup for audio files now. See the [attributes file](https://github.com/Scrivener07/FO4_Games/blob/master/.gitattributes) to see whats currently tracked.

**Comment by TheWhiteCollarPlayers** [comment]
Closing this, this is an ongoing and iterative process that doesnt need an issue to track it
multiple commits in the near future will contain voice changes
