### ISSUE TITLE
Bugs from MxR's review:

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#117]
**MxR's Video:** https://youtu.be/rP7kRxdzuN8
1) NPC's duplicating after playing the game? Just harry or all? Or not our issue?

2) Other bar patrons dont react when killing dealer, just Harry and one in Third Rail or all? A simple faction issue but I thought I tested this, guess I need to go back through

**Comment by Scrivener07** [comment]
This is MxR's video: https://youtu.be/rP7kRxdzuN8

**Comment by TheWhiteCollarPlayers** [comment]
Factions fixed, NPC's will now appropriately react when you attack one of our npc's 
further testing was unable to replicate the duplicating dealer, closing this, if it pops up again Ill reopen this
https://github.com/Scrivener07/FO4_Games/commit/d5694328a9754903ecaa50fc64f49ec361ebc02a
