### ISSUE TITLE
To do: Improve Blackjack table to require an assigned settler to function.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#16]

**Comment by TheWhiteCollarPlayers** [comment]
This enhancement is basically finished and takes an iota of CK work, (big thanks to Jonathan Ostrus for teaching me how to do it). The only thing left to do is attach an animation point and make it assignable (so the player assigns a dealer to the table first before they can play). After the Alpha is released, we need to have a discussion on implementing the table into the settlement build list. (only after a quest? after a magazine? or just as soon as the esp loads?)

**Comment by Scrivener07** [comment]
At this point we have arrived at a magazine. The art is looking pretty good so far.

![Magazine](https://cdn.discordapp.com/attachments/309838136387698689/328937822847238174/Screenshot_140.png "Magazine")

![Magazine](https://cdn.discordapp.com/attachments/309838136387698689/328937842665586688/Screenshot_141.png "Magazine")

Asset Source
https://en.wikipedia.org/wiki/Macfadden_Communications_Group

**Comment by TheWhiteCollarPlayers** [comment]
I want to leave this issue open, I eventually want to add an assignable dealer to the settlement object

**Comment by Scrivener07** [comment]
The blackjack table is now a constructible item.

**Comment by TheWhiteCollarPlayers** [comment]
Reopening this issue as it is contained within my esp which I have not yet committed, and to keep track of progress on it (into a NPC assignable object and so forth)

**Comment by TheWhiteCollarPlayers** [comment]
Closing this, merging it to my other issue to do list
