### ISSUE TITLE
AI personalities for the dealer and opponent players.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#18]

**Comment by TheWhiteCollarPlayers** [comment]
Where are we on this?

**Comment by Scrivener07** [comment]
The personalities are already pretty much done. The human, and dealer already have unique personalities, the other bots do too. Its just the other bot need to be given an **interesting** unique personality.

The two bot personalities I have thought of so far are the `Whale` and the `Swatter`.

The whale will override the default wager behavior with one that will always wager the players bet times three and plus 50. They will always be the highest betting player at the table.
```
int Function BehaviorWager()
	return (BlackJack.Players.Human.Wager * 3) + 50
EndFunction
```


The swatter will override the default turn behavior with one that favors hitting for a new card. They really like to hit on their turn.
```
int Function BehaviorTurn()
	If (Score <= 18)
		return OptionHit
	Else
		return OptionStand
	EndIf
EndFunction
```

**Comment by TheWhiteCollarPlayers** [comment]
Nice! I like the idea of different personalities, how many of those were you thinking of doing? You could also do ones such as "the cheapskate" or "the conservative".

**Comment by Scrivener07** [comment]
I want there to be 6 unique players counting the dealer and human. That's one player for each possible seat at a blackjack table. (1 dealer, 5 gamblers).

The base default `Player` class is a simple gambler AI with nothing special. It returns a hardcoded wager of 20 and will hit until their score is less than or equal to 16, stands on 17 or greater. With that, it is very simple to extend this `Player` base by overriding the functions involved in their behavior. 

We have the following so far.
* Dealer
* Human
* Bot Whale
* Bot Swatter
* Bot Default
* Bot Default

If you count the default bot as a unique player then that leaves room for one more personality.
How exactly does a "cheapskate" or "conservative". play their game? What kind of decisions do they make?

This one might be more than I want to do right now but as an example consider the "card counter".

> The card counter personality when deciding whether to hit or stand, may peek at the card they would draw if they were to hit. If it is safe to hit then they will.

The AI personalities may be something we can use to increase the difficulty of a game among other factors.

**Comment by TheWhiteCollarPlayers** [comment]
Card counter would be interesting, a cheap skate / conservative will always bet low amounts and take very few risks so he wont hit on higher cards and try to play it safe.

**Comment by Scrivener07** [comment]
I like the idea of randomly selected personalities too. Its pretty bare bones at this point but Ive left a lot of room to expand this area in the future. The personalities are not interesting enough to close this issue so I guess leave it open until we have time to revisit this.

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as we have taken a different approach with blackjack, if we wish to pursue this later on, we can reopen
