### ISSUE TITLE
To Do: Make Gambling NPC and Place in these locations

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#19]
Places to add gambling NPC's (feel free to add more to this list if you want):
Commonwealth Locations:
-Dugout Inn [x] "coc DmndDugoutInn01"
-Colonial Taphouse [x] "coc DmndStandsTaphouse01"
-Third Rail [x] "coc GoodneighborTheThirdRail"
-Vault 81 [x] "coc Vault81"
-Prydwen [x] "coc PrydwenHull01"
-Railroad HQ[x] "coc RailroadHQ01"
Far harbor Locations:
-Acadia[x] "coc DLC03Acadia"
-Church of Children of Atom (The Nucleus) [x] "coc DLC03Nucleus"
-Far Harbor Town Bar [x] "coc DLC03FarHarborLastPlank"
Nuka World Locations:
-The Pack HQ[x] "coc DLC04HubPackLair"
-The Operators HQ[x] "coc DLC04HubOperatorLair01"
-The Disciples HQ[x] "coc DLC04HubFizztopMountainInterior01"
-Market in Nuka World[x] "coc NukaTownMarket01"

**Comment by Scrivener07** [comment]
Diamond City and Goodneighbor are good locations. I'm not sure about Far Harbor or Nuka World because I haven't played them much. Combat Zone sounds cool but I have never gone there without killing everyone.

**Comment by TheWhiteCollarPlayers** [comment]
I haven't played Nuka World much, but Far Harbor is a good place for it, the bar there at least. It's impossible to go to the combat zone without killing anyone, but I had an idea about after you kill everyone you could go back a few days later and a little gambling room in the back would be set up, just to give the place some more life.

**Comment by Scrivener07** [comment]
Far Harbor sounds good if you know of a fitting bar there. The combat zone sounds good too if you can sneak the gambling room in. I'm sure we can find one for nuka world too if we poke around.

**Comment by TheWhiteCollarPlayers** [comment]
Ya, the combat zone would take a little more quest work than the others, so maybe that could wait until after the Alpha release

**Comment by TheWhiteCollarPlayers** [comment]
I'm cleaning up this thread and editing the list.

**Comment by TheWhiteCollarPlayers** [comment]
Places to add gambling NPC's (feel free to add more to this list if you want):
Commonwealth Locations:
-Dugout Inn
-Colonial Taphouse
-Third Rail
-Vault 88
-Prydwen
-Railroad HQ(edited)
Far harbor Locations:
-Acadia
-Church of Children of Atom (The Nucleus)
-Far Harbor Town Bar
Nuka World Locations:
-Each of Raider Faction HQ's (The Pack, The Disciples, The Operators)
-Market in Nuka World
-Hubologists Camp(edited)

**Comment by Scrivener07** [comment]
Another possibility by random encounter with a traveling gambling NPC.

**Comment by TheWhiteCollarPlayers** [comment]
Need to finish the quest for Vault 81 dealer after the file issue I had

**Comment by TheWhiteCollarPlayers** [comment]
Fixed vault 81 dealer quest with commit below. Still chugging away on NPC's
https://github.com/Scrivener07/FO4_Games/commit/06e0cb6dbfa99912eeb5d9a9bc36587f948b4460

**Comment by TheWhiteCollarPlayers** [comment]
Prydwen dealer implemented with commit below. I have a concern there might be some missing files that I need to stage, so outside testing would be helpful. 
https://github.com/Scrivener07/FO4_Games/commit/e03f6b5bff88480902d44471855755057425da65

**Comment by TheWhiteCollarPlayers** [comment]
Last commonwealth NPC is implemented! Also added missing actor files. With the commit below, commonwealth implementation is essentially done (minor tweaks needed like adding voice files). Leaving this issue open to track implementation of DLC area NPC's. DLC NPC's will be a new branch and a separate esp. 
https://github.com/Scrivener07/FO4_Games/commit/7d6e37feb89aa961f901d4caac08b9badc595835

**Comment by TheWhiteCollarPlayers** [comment]
Starting on Far Harbor, did some of it via stream for Cascadia so I have to go back and do dialogue

**Comment by TheWhiteCollarPlayers** [comment]
Harry-Dugout Inn-Diamond City
![harry-dugoutinn-diamondcity](https://user-images.githubusercontent.com/28495967/36766245-ada0f9e4-1bfa-11e8-89b5-8fac84f61c5d.png)

**Comment by TheWhiteCollarPlayers** [comment]
Mr. Wallace-Colonial Taphouse-Diamond City
![mr wallace-colonial taphouse-diamondcity](https://user-images.githubusercontent.com/28495967/36766264-c40a30ce-1bfa-11e8-92bc-46b09c964ea9.png)

**Comment by TheWhiteCollarPlayers** [comment]
Douglas-Third Rail-Goodneighbor
![douglas-third rail goodneighbor](https://user-images.githubusercontent.com/28495967/36766277-d2ccb5fa-1bfa-11e8-9fc5-2a842cea1093.png)

**Comment by TheWhiteCollarPlayers** [comment]
Jackson-Diner-Vault81
![jackson-diner-vault 81](https://user-images.githubusercontent.com/28495967/36766297-e27ca00a-1bfa-11e8-99c8-7b7d7d8796c4.png)

**Comment by TheWhiteCollarPlayers** [comment]
Scribe Harrison-Mess Hall-Prydwen Airship
![scribe harrison-mess hall-prydwen airship](https://user-images.githubusercontent.com/28495967/36766309-ed2d53dc-1bfa-11e8-9ae4-4cb629657330.png)

**Comment by TheWhiteCollarPlayers** [comment]
Toby-Railroad HQ-Old North Church
![screenshot 2](https://user-images.githubusercontent.com/28495967/36936854-12fed4c8-1ed0-11e8-8d1a-8c1479897b04.png)

**Comment by TheWhiteCollarPlayers** [comment]
Far Harbor implementation is complete with this commit. It is ready to go out whenever we want to do that. Nuka World and Merged DLC plugin still to come.
https://github.com/Scrivener07/FO4_Games/commit/7a72d887c8b9471e979e740df72f909f13b9ac48

**Comment by TheWhiteCollarPlayers** [comment]
Terry 'Busch' Baldwater-Last Plank-Town of Far Harbor
![screenshot 5](https://user-images.githubusercontent.com/28495967/37624811-8df06826-2b97-11e8-99e3-bc63e25214fa.png)

**Comment by TheWhiteCollarPlayers** [comment]
Elliott-Acadia-Island of Far Harbor
![screenshot 4](https://user-images.githubusercontent.com/28495967/37624824-a4547878-2b97-11e8-90a9-2b3b00090d4a.png)

**Comment by TheWhiteCollarPlayers** [comment]
Brother Julius-Nucleus-Island of Far Harbor
![screenshot 6](https://user-images.githubusercontent.com/28495967/37624846-bb463454-2b97-11e8-9971-4de95be0a4b4.png)

**Comment by TheWhiteCollarPlayers** [comment]
Max-Pack Den-Nuka World Hub
![screenshot 7](https://user-images.githubusercontent.com/28495967/37728060-4f974b1e-2d07-11e8-84e2-e968342abe93.png)

**Comment by TheWhiteCollarPlayers** [comment]
Zilch-Operator Hideout-Nuka World Hub
![screenshot 8](https://user-images.githubusercontent.com/28495967/37728251-c3a4040c-2d07-11e8-8941-bf3599d914ca.png)

**Comment by TheWhiteCollarPlayers** [comment]
Rufio-Fizztop Mountain-Nuka World Hub
![screenshot 9](https://user-images.githubusercontent.com/28495967/37731864-68864c38-2d11-11e8-9267-f707f1ec436a.png)

**Comment by TheWhiteCollarPlayers** [comment]
3 Gang specific NPC's complete. 2 NPC's left.
https://github.com/Scrivener07/FO4_Games/commit/16fc6b3f54b3e34d0502e50db9abb72288dc54f2

**Comment by TheWhiteCollarPlayers** [comment]
Removing the Hubologist NPC from this list, they have that big quest that is very specific to how many people they have so it wouldn't fit right, one NPC for NW left.

**Comment by TheWhiteCollarPlayers** [comment]
Sammy-Market-Nuka Town USA
![screenshot 10](https://user-images.githubusercontent.com/28495967/37734831-540f8ba8-2d1a-11e8-92e4-3cb7292ccf8d.png)

**Comment by TheWhiteCollarPlayers** [comment]
Nuka World Implementation is complete with this commit, closing this issue!
https://github.com/Scrivener07/FO4_Games/commit/86e47baf5bb1ccc6a0d1655ab5c1e53593d0ab68
