### ISSUE TITLE
Perks

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#2]
I like the idea of perks that can be earned by completing challenges related to gambling.  An idea for one of these perks went something like this.

**Perk** Luck of the Draw
**Description** You always keep a trick up your sleeve.
_When you accept this perk, choose a card. You hide this card in your boot. During a card game you may either choose to draw your next card or play the card in your boot._

An example of a gambling challenge to complete in order to earn a perk might go something like this.
**Challenge**: Score a black jack three times in a row to earn _Luck of the Draw_.

**Comment by TheWhiteCollarPlayers** [comment]
Not necessary for a first playable build, reflagging as an enhancement.

**Comment by TheWhiteCollarPlayers** [comment]
I like the idea of perks and I want to do them eventually but I think this falls pretty low on the priority tree. I would say lets finish the games we wanna do then we can come back to this.

**Comment by TheWhiteCollarPlayers** [comment]
Although I will also say that the perk system in FO4 is pretty screwy so adding more to it might be more cumbersome and work than it is worth

**Comment by Scrivener07** [comment]
Its not a priority. I renamed the project this issue belongs to in order to make this more clear.
![capture](https://user-images.githubusercontent.com/1912967/35191852-827cfdb8-fe53-11e7-907e-a92831be6c80.PNG)

**Comment by Scrivener07** [comment]
Closing this. There are no longer plans for perks in the vanilla implementation.
