### ISSUE TITLE
An ace cards value is not calculated correctly in blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#22]
The ace is returning its "soft" score.

**Comment by Scrivener07** [comment]
Two examples. The ace is returning its "soft" score.
![screenshot19](https://user-images.githubusercontent.com/1912967/27143106-3126bd60-50fb-11e7-9685-26de8dceb9b9.png)
![screenshot20](https://user-images.githubusercontent.com/1912967/27143105-312655be-50fb-11e7-9e6c-45c84cc23c9f.png)

**Comment by TheWhiteCollarPlayers** [comment]
A simple condition check will fix that: 
```
if (11+PlayerTotal > 21) 
     PlayerTotal = PlayerTotal + 11

else 

PlayerTotal = Player Total + 10

end
```

**Comment by Scrivener07** [comment]
Thats nearly exactly what I have in the [rules](https://github.com/Scrivener07/FO4_Gambling/blob/eac26ef6b5d6717e6d1e346f01189d424138c34c/Data/Scripts/Source/FO4_Gambling/Gambling/BlackJack/Components/Rules.psc#L35). ToScore will convert a Card into its score value. Maybe the problem is where the whole hands score is calculated. Im still taking a look at this.

**Comment by TheWhiteCollarPlayers** [comment]
Is this still a bug? I believe it works now

**Comment by Scrivener07** [comment]
Ill feel confident if someone else plays 10 games and doesnt notice anything weird. You think you can get in 10 games? Maybe do 5 games and then quit the table, then do another 5. Anything you think might break it, do it.

**Comment by TheWhiteCollarPlayers** [comment]
Oh ya I will put it through the paces

**Comment by TheWhiteCollarPlayers** [comment]
I'll get on that in a bit

**Comment by Scrivener07** [comment]
Hit that `Print Screen` button if you catch any bugs.

**Comment by TheWhiteCollarPlayers** [comment]
Is this officially squashed?

**Comment by TheWhiteCollarPlayers** [comment]
I believe this is fixed now, but if you want to do more testing let me know, otherwise we can close this

**Comment by Scrivener07** [comment]
Ace cards are now calculating score value properly.
