### ISSUE TITLE
The blackjack table started with odd positioning.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#23]
A screenshot of the issue is included below. This happened immediately after the loading screen was finished. The wager message paused the game in this camera position which appears to be from the player still havok settling after loading into the level. Right after closing the wager message the camera corrected itself almost immediately.

I have been unable to reproduce this bug in game.
![bug](https://user-images.githubusercontent.com/1912967/27135489-9427ea16-50e6-11e7-885e-30d0194fd489.png)

**Comment by TheWhiteCollarPlayers** [comment]
I wouldn't worry about it until I can reproduce it.

**Comment by TheWhiteCollarPlayers** [comment]
Also it isn't that big of a deal anyway

**Comment by Scrivener07** [comment]
I have seen it happen two or three more times since posted this. I still cant reproduce it predictably.

**Comment by TheWhiteCollarPlayers** [comment]
I'll keep my eyes peeled

**Comment by TheWhiteCollarPlayers** [comment]
I also have experienced this bug, although I cannot seem to repeat it every time it seems random

**Comment by Scrivener07** [comment]
I have a good chance to figure this out while I investigate issue #30

**Comment by Scrivener07** [comment]
This has been fixed as far as I can tell. I simply added a wait to the table component.
