### ISSUE TITLE
Cannot abort game if wager was canceled.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#24]
The player can wager a `0` bet and still be allowed to play the game at this point. Bug or feature?

**Comment by TheWhiteCollarPlayers** [comment]
Bug for sure. You should not be allowed to play if you don't have money to bet, just how casinos or bars work, because it costs money to have the dealer standing there dealing you cards, so either pay or gtfo.

**Comment by Scrivener07** [comment]
Marked it as a bug. Ill make sure this is covered when wagering is done.

**Comment by TheWhiteCollarPlayers** [comment]
Have you started working on this? Thoughts about how to fix it? In C I would recommend a simple GoTo statement whenever the player hits cancel, but I don't know how that works in papryus

**Comment by Scrivener07** [comment]
It cancels really good, give it a try in game.

**Comment by TheWhiteCollarPlayers** [comment]
I will test these out and then revisit this issue

**Comment by TheWhiteCollarPlayers** [comment]
Current bug state: 
Exiting via settlement object needs to be moved to next to the table in stead of on top of, ideally we should add some sort of visual reference on the table to indicate where the player spawns after they play so they know how to position the table. 
Exiting via dialogue wither when cancelling or simply quitting does not work at all and leaves the player stranded in the GamblingCell

**Comment by Scrivener07** [comment]
Created issue #31 and issue #32 for these things.

**Comment by Scrivener07** [comment]
Closing this as the original issue is now solved.
