### ISSUE TITLE
Track the human players best stats and scores.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#25]
An idea to track the humans best stats and scores. A stat I had in mind was the highest amount of winnings you have won in a single session. A session starts the moment you sit down to play, and ends when you get up from the table. Another stat that would be cool to track is the amount of blackjack games that have been played. As always, your comments are appreciated.

Here is a list of stats.
* The total number of games played over a career.
* The total winnings and losses over a career.
* The highest winnings you have ever walked away from a table with.
* The total number of blackjacks over a career.

**Comment by TheWhiteCollarPlayers** [comment]
Good idea, I have no absolutely no idea where or how we would display that information for the player but here are some stat ideas:

Number of games played
Total winnings (could be positive or negative)
Winnings of last session (what you suggested)
Number of blackjacks

**Comment by Scrivener07** [comment]
Good ideas. I edited the issue with a list.

**Comment by TheWhiteCollarPlayers** [comment]
Since you edited the list, I'm deleting old comments to help keep the thread concise

**Comment by TheWhiteCollarPlayers** [comment]
Should we update this thread to reflect the current build of the mod? Tracking earnings only during each sit at the table? Or do you want to eventually do this?

**Comment by TheWhiteCollarPlayers** [comment]
Merging this into https://github.com/Scrivener07/FO4_Games/issues/100
Closing
