### ISSUE TITLE
Sim Settlements Plot Addon

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#27]
How about we create an SS addon plot for playing classic games like blackjack.

[Sim Settlements Toolkit](https://www.simsettlements.com/web/wiki/index.php?title=Toolkit)

**Comment by Scrivener07** [comment]
Some advice from kinggath of Sim Settlements.

> You're going to want to extend the WorkshopObjectScript for your furniture object, and override this method: AssignActor   so that you can assign them to an alias on your new quest to manage the dialogue.
> The workshop dialogue is handled by WorkshopParent, so you can use some of that as a template and steal dialogue lines so that their other lines can match the vanilla stuff.
> 

> I don't think it was intended to be, but the inheritance is reasonable enough in papyrus that you can extend pretty much anything. Especially with the native Parent.Method support.

> The biggest hurdle is how much WorkshopParent tries to get involved. I'd tell you to decompile the SS code for ideas on some of the hoops you might have to jump through, but I think it's a little tough to follow now and the primary reason for it's complexity is overriding the default behavior of one assignment per settler.
> I think for getting a standalone release functioning, just extending WorkshopObjectScript should be pretty simple overall.

**Comment by TheWhiteCollarPlayers** [comment]
After we are at a comfortable point with the mod, we can discuss this, but it is definitely something I want to do

**Comment by TheWhiteCollarPlayers** [comment]
An update: user Uituit has created the plots for us, all I need to do is add our custom furniture to each level and boom done. Will be focusing on this soon!

**Comment by TheWhiteCollarPlayers** [comment]
The sim settlements addon is pushed to the Nexus! Closed!
