### ISSUE TITLE
New, 52 Card Pickup

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#29]
You play 52 card pickup. A deck of 52 cards is flung around an area. The player must race the clock to pick up all the cards. 

This game is certainly a classic!

**Comment by TheWhiteCollarPlayers** [comment]
Hahahaha ummmm I don't think many people would be interested in that but if you wanna do it, I'm not gonna stop you hahaha

**Comment by Scrivener07** [comment]
There is no stopping me now! It's a silly idea I want to do at some point, but not right now.

**Comment by Scrivener07** [comment]
Closing this. I may revisit silly games in the future.
