### ISSUE TITLE
Gun remains drawn when playing

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#30]
If you activate the table with your weapon drawn, it will be visible when you play the game.

**Comment by Scrivener07** [comment]
Thanks! I forgot about this one. I even have it captured on a youtube video, still forgot.

**Comment by Scrivener07** [comment]
This may be fixed with commit bcdc6a2

**Comment by TheWhiteCollarPlayers** [comment]
I'll test it as soon as I can

**Comment by Scrivener07** [comment]
This appears to be fixed now.
