### ISSUE TITLE
Cannot exit game properly from dialogue.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#32]
Exiting via dialogue when cancelling or simply quitting does not work at all and leaves the player stranded in the `GamblingCell`.

**Comment by Scrivener07** [comment]
Issue #31

**Comment by TheWhiteCollarPlayers** [comment]
Is this fixed? It appears so to me

**Comment by Scrivener07** [comment]
This is definitely fixed with release [v0.0.0.1-devonly](https://github.com/Scrivener07/FO4_Games/releases/tag/v0.0.0.1-devonly) on commit 4088776
