### ISSUE TITLE
The texture sizes are very large for a release. Possibly reduce the size.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#33]
The card textures are 1K which is overkill for the distance they are viewed.

Use a 64x64 texture instead. I did a quick search and found the [texture optimization project](http://www.nexusmods.com/fallout4/mods/19061/). I dont know much about art stuff, and even less about fallout 4 art stuff, so there are some things here for one of us to figure out. Even if we are reducing the texture size we should maintain a version of the highest quality we have available.

**Comment by TheWhiteCollarPlayers** [comment]
I can't see what you posted, did you upload an image or something? You could just list which textures you are referring to, also why do you say they are too large?

**Comment by Scrivener07** [comment]
**E** is an author who I trust and this is something he pointed out. The card textures are 1K which is overkill for the distance they are viewed. He suggested using a 64x64 texture instead. I did a quick search and found the [texture optimization project](http://www.nexusmods.com/fallout4/mods/19061/). I dont know much about art stuff, and even less about fallout 4 art stuff, so there are some things here for one of us to figure out. Even if we are reducing the texture size we should maintain a version of the highest quality we have available.

**Comment by Scrivener07** [comment]
Sorry. I did forget to finish typing the issue the first time.

**Comment by TheWhiteCollarPlayers** [comment]
I can work on this, however.... I'm worried about the ramifications of applying the new textures to the existing assets, what do you need from me? and how easy is it to swap the textures?

**Comment by TheWhiteCollarPlayers** [comment]
I will fix this just before we release, can run the textures through Elric

**Comment by Scrivener07** [comment]
We need to try a few sizes first before commiting to one for release. 64x64 might be too small. We cant afford to lose any legibility. If we need them to be 1k, then we need them to be 1k. This applies at least to the cards that are actually used in a card game. If you want to release standalone cards that can be picked-up and put-down then legibility is not nearly as important.

**Comment by TheWhiteCollarPlayers** [comment]
Gonna close this for the time being, we have the texutres packed and set now, this might come up later when we start making more textures for caravan decks etc.

**Comment by Scrivener07** [comment]
Agreed
