### ISSUE TITLE
Cannot double down in blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#35]

**Comment by TheWhiteCollarPlayers** [comment]
This should be rather simple to code, add another option to the player's turn so they either choose Hit Stand or Double Down, and of course a condition to check for which option, then if they chose double down, double their wager (removing the same amount of caps as their initial wager) and then only deal one more card, then proceed as normal

**Comment by TheWhiteCollarPlayers** [comment]
per our voice discussion: this is considered necessary for a playable release

**Comment by TheWhiteCollarPlayers** [comment]
Updated labels, same as the cannot surrender and take insurance issues

**Comment by TheWhiteCollarPlayers** [comment]
Merging this into 
https://github.com/Scrivener07/FO4_Games/issues/100
closing
