### ISSUE TITLE
Cannot split in blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#36]

**Comment by TheWhiteCollarPlayers** [comment]
I also would not consider splitting necessary for a first playable release, however I would love to have it in the final version of Blackjack

**Comment by TheWhiteCollarPlayers** [comment]
per our voice discussion: this is considered necessary for a first release

**Comment by TheWhiteCollarPlayers** [comment]
I am marking this as enhancement, same kinda thing as the cannot surrender and insurance issues

**Comment by TheWhiteCollarPlayers** [comment]
Merging into https://github.com/Scrivener07/FO4_Games/issues/100
Closing
