### ISSUE TITLE
Cannot take insurance in blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#38]

**Comment by TheWhiteCollarPlayers** [comment]
Don't know if this should have bug label, would not consider insurance necessary for a first playable build.

**Comment by TheWhiteCollarPlayers** [comment]
per our voice discussion: this is considered extra/optional

**Comment by Scrivener07** [comment]
I changed the label to enhancement.

**Comment by TheWhiteCollarPlayers** [comment]
Leaving this open, but just like the cannot surrender issue, dont really need to revisit this until we are ready to do a second pass on everything for optimzation / improvements

**Comment by TheWhiteCollarPlayers** [comment]
Merging this into 
https://github.com/Scrivener07/FO4_Games/issues/100
closing
