### ISSUE TITLE
Cannot surrender in blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#39]

**Comment by TheWhiteCollarPlayers** [comment]
What do you mean by surrender?

**Comment by Scrivener07** [comment]
Check out the wiki https://github.com/Scrivener07/FO4_Gambling/wiki
**Surrender**: Give up a half-bet and retire from the game.

**Comment by TheWhiteCollarPlayers** [comment]
Read the wiki, one thing about it (not that big a deal) that magazine location is not permanent I will most likely move it to a more appropriate spot for the player to find, somewhere in one of the bars where they can play most likely.

**Comment by TheWhiteCollarPlayers** [comment]
Per our voice discussion: this is considered extra/optional

**Comment by Scrivener07** [comment]
I changed the label to enhancement.

**Comment by TheWhiteCollarPlayers** [comment]
I will leave this issue open but this issue seems like something we can put as very low on our priority list. I would also say that we wouldnt need to revisit this issue until we want to do a second pass on optimization and improvements and such

**Comment by TheWhiteCollarPlayers** [comment]
Closing this, merged into 
https://github.com/Scrivener07/FO4_Games/issues/100
