### ISSUE TITLE
Magazine does not have a GUI vault boy icon.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#41]
Barstool Games Weekly is using the awesome tales vault boy icon.
![screenshot59](https://user-images.githubusercontent.com/1912967/27714343-50edd3fe-5cfe-11e7-8ba2-482d97468ce0.png)

**Comment by TheWhiteCollarPlayers** [comment]
Thanks, I'll look into this as soon as the fresh install is complete

**Comment by TheWhiteCollarPlayers** [comment]
Per our voice discussion:
we need a standard vault boy logo to use in relevant UI positions, I will see if the Cascadia people can come up with that for us

**Comment by TheWhiteCollarPlayers** [comment]
I have fixed this, the table is now added the same way other objects are added in the vanilla game. It is invisible until you pick up the magazine, so this is no longer an issue. This is technically fixed in my plugin, but until that change is merged into the esm I will leave this open.

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as it is fixed in the current build of the mod
