### ISSUE TITLE
Vanilla user interface for blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#42]
We need a fully featured interface that does not rely on F4SE. With [HUD Framework](http://www.nexusmods.com/fallout4/mods/20309/), we can still add hud widgets without any dependency to F4SE which would allow us to support Xbox. These hud widgets do have some limitations, in particular, the widgets cannot send data back to papyrus but we can send data from papyrus to the hud widgets. To summarize that, hud widgets can only receive data without F4SE.

 Something that the vanilla messagebox does is return a user selected option from a pre-made messagebox menu. Messageboxes are a bit clunkly but in the vanilla interface system for blackjack we will still need a messagebox at times we need to process input from the player within papyrus. 

Even though we cant completely get rid of the messageboxes for an Xbox version we can still do quite a bit to still make it look great.

### Some things a widget can display about the current player.
* Current Score
* Current Bid
* Total Caps (**Human Only**)
* The exact details of each card in hand (suit, rank, color, etc)
* The number of turns taken this match. A `turn` is a play action (hit, stand, double, split).
* The scoring result where the player's score is compared to the dealers.

### Some things a widget can display about the current game session.
* The current phase name
* The current player's name. (more like a label)
* Total Wins/Losses for this session.
* Total number of matches played this session.
* The status of the last turn that occurred.  A `turn` is a play action (hit, stand, double, split).

### Some things we still need a messagebox for the purpose of user input.
* Wagering a bet amount
* Deciding a turn action. A `turn` is a play action (hit, stand, double, split).
* Yes/No for the "play again" prompt.

This is how it looked in Fallout New Vegas. Looks like a good design to start with.
![capture](https://user-images.githubusercontent.com/1912967/27805407-6fe23fd2-6002-11e7-9016-4a2165a3bf5c.PNG)

**Comment by Scrivener07** [comment]
Related to issue #7

**Comment by Scrivener07** [comment]
Here is a step by step of current UI going through its paces.

![screenshot64](https://user-images.githubusercontent.com/1912967/27771731-0c5fc5ae-5f23-11e7-85cc-684262988fe7.png)
![screenshot65](https://user-images.githubusercontent.com/1912967/27771732-0c604b6e-5f23-11e7-8cd9-fc7ea8198cd2.png)
![screenshot66](https://user-images.githubusercontent.com/1912967/27771736-0c660446-5f23-11e7-8c9d-cff18bdb29f4.png)
![screenshot67](https://user-images.githubusercontent.com/1912967/27771735-0c61de5c-5f23-11e7-9f2b-fe30d5e200fe.png)
![screenshot68](https://user-images.githubusercontent.com/1912967/27771733-0c60a1e0-5f23-11e7-9e88-40288dc47d5c.png)
![screenshot69](https://user-images.githubusercontent.com/1912967/27771734-0c61bf94-5f23-11e7-9cba-7a27babe0341.png)
![screenshot70](https://user-images.githubusercontent.com/1912967/27771740-0c6cabd4-5f23-11e7-9a1d-bbd78140330d.png)
![screenshot71](https://user-images.githubusercontent.com/1912967/27771738-0c6a7288-5f23-11e7-9d94-0bb2b23adf12.png)
![screenshot72](https://user-images.githubusercontent.com/1912967/27771737-0c69d92c-5f23-11e7-8373-9b11446b3105.png)
![screenshot73](https://user-images.githubusercontent.com/1912967/27771739-0c6b7fde-5f23-11e7-9824-94a45d1b683c.png)
![screenshot74](https://user-images.githubusercontent.com/1912967/27771741-0c709d8e-5f23-11e7-81d9-052c6fa2c167.png)
![screenshot75](https://user-images.githubusercontent.com/1912967/27771742-0c71e388-5f23-11e7-9efa-554fc841ac25.png)
![screenshot76](https://user-images.githubusercontent.com/1912967/27771743-0c731438-5f23-11e7-885c-cf079a0848c5.png)
![screenshot77](https://user-images.githubusercontent.com/1912967/27771746-0c76ecb6-5f23-11e7-8b32-3a7af311dbe0.png)
![screenshot78](https://user-images.githubusercontent.com/1912967/27771745-0c765576-5f23-11e7-8a6e-c169ef20c409.png)
![screenshot79](https://user-images.githubusercontent.com/1912967/27771744-0c760224-5f23-11e7-9bac-ba66a36e5457.png)
![screenshot80](https://user-images.githubusercontent.com/1912967/27771747-0c793566-5f23-11e7-8ca9-2ccc7598e35a.png)
![screenshot81](https://user-images.githubusercontent.com/1912967/27771748-0c7b982e-5f23-11e7-934c-f4ad1cf7e19d.png)
![screenshot82](https://user-images.githubusercontent.com/1912967/27771749-0c7d225c-5f23-11e7-9a4b-06ac63b2daeb.png)
![screenshot83](https://user-images.githubusercontent.com/1912967/27771752-0c820600-5f23-11e7-924f-018968d91447.png)
![screenshot84](https://user-images.githubusercontent.com/1912967/27771750-0c7fcfe8-5f23-11e7-87fc-1556e6efc7c6.png)
![screenshot85](https://user-images.githubusercontent.com/1912967/27771751-0c816006-5f23-11e7-898e-6ecb9015638d.png)
![screenshot86](https://user-images.githubusercontent.com/1912967/27771756-0c8a3604-5f23-11e7-8c76-e2337927ed17.png)
![screenshot87](https://user-images.githubusercontent.com/1912967/27771753-0c845a40-5f23-11e7-9582-77c5fd5a5dbc.png)
![screenshot88](https://user-images.githubusercontent.com/1912967/27771754-0c86bca4-5f23-11e7-9185-5f53a05d3524.png)
![screenshot89](https://user-images.githubusercontent.com/1912967/27771755-0c883458-5f23-11e7-9a8e-1523c6c687c8.png)
![screenshot90](https://user-images.githubusercontent.com/1912967/27771764-0c99341a-5f23-11e7-9a2e-9b2c51ac0641.png)
![screenshot91](https://user-images.githubusercontent.com/1912967/27771757-0c8ae8b0-5f23-11e7-852a-9b87e132f535.png)
![screenshot92](https://user-images.githubusercontent.com/1912967/27771758-0c8d84c6-5f23-11e7-873f-8994ca975e2f.png)
![screenshot93](https://user-images.githubusercontent.com/1912967/27771759-0c8ff8d2-5f23-11e7-8054-b64aeea2c32c.png)
![screenshot94](https://user-images.githubusercontent.com/1912967/27771760-0c93a842-5f23-11e7-8958-053e546d56e5.png)
![screenshot95](https://user-images.githubusercontent.com/1912967/27771761-0c94ee14-5f23-11e7-825d-89a1e32283c0.png)
![screenshot96](https://user-images.githubusercontent.com/1912967/27771763-0c99194e-5f23-11e7-8178-55a43ac77d37.png)
![screenshot97](https://user-images.githubusercontent.com/1912967/27771762-0c978732-5f23-11e7-8ff7-7b7b444c2804.png)
![screenshot98](https://user-images.githubusercontent.com/1912967/27771765-0c99a4cc-5f23-11e7-9388-b8218535f83c.png)
![screenshot99](https://user-images.githubusercontent.com/1912967/27771766-0c9e59a4-5f23-11e7-9806-58ba33996593.png)
![screenshot100](https://user-images.githubusercontent.com/1912967/27771767-0c9f2104-5f23-11e7-8359-1627c1ddc064.png)
![screenshot101](https://user-images.githubusercontent.com/1912967/27771768-0ca14dbc-5f23-11e7-9076-02d9c418c1f0.png)
![screenshot102](https://user-images.githubusercontent.com/1912967/27771770-0ca305b2-5f23-11e7-9c6b-9cb7c43d84ef.png)
![screenshot103](https://user-images.githubusercontent.com/1912967/27771771-0ca40f02-5f23-11e7-9801-d0b3d2464400.png)
![screenshot104](https://user-images.githubusercontent.com/1912967/27771769-0ca25194-5f23-11e7-9fc2-1a0a7cb15996.png)
![screenshot105](https://user-images.githubusercontent.com/1912967/27771773-0caab0e6-5f23-11e7-9310-862f95faa6fb.png)
![screenshot106](https://user-images.githubusercontent.com/1912967/27771772-0caab51e-5f23-11e7-9da9-18383efa6299.png)
![screenshot107](https://user-images.githubusercontent.com/1912967/27771774-0cab3304-5f23-11e7-879e-cdcdbe58b624.png)
![screenshot108](https://user-images.githubusercontent.com/1912967/27771775-0cac8f1a-5f23-11e7-84b7-f348bb0f012d.png)
![screenshot109](https://user-images.githubusercontent.com/1912967/27771776-0cacf522-5f23-11e7-8126-14cbaa62855f.png)
![screenshot110](https://user-images.githubusercontent.com/1912967/27771777-0cade3ec-5f23-11e7-9507-faa73e6ce420.png)

**Comment by TheWhiteCollarPlayers** [comment]
I completely agree, we might need to have a voice meeting about this

**Comment by Scrivener07** [comment]
Edited the main post at the top.

**Comment by Scrivener07** [comment]
I also had the idea to position an invisible activator in front of the player for the activate text. If this idea works out we can collect some input from the player in this way too.

**Comment by Scrivener07** [comment]
I figured out how I might be able to use activate text for user input. These are cool because they dont obscure the player's view and they DONT pause the game world like a messagebox would.

![screenshot112](https://user-images.githubusercontent.com/1912967/27774065-478f01e2-5f57-11e7-828e-a39cfcefccce.png)

**Comment by Scrivener07** [comment]
Ive got a status widget semi-working today.

![screenshot124](https://user-images.githubusercontent.com/1912967/27806278-930273e2-6007-11e7-881f-35cea780fb91.png)
![screenshot125](https://user-images.githubusercontent.com/1912967/27806280-930426f6-6007-11e7-957e-d7e7a69e8324.png)

**Comment by TheWhiteCollarPlayers** [comment]
Wow, that is awesome stuff, that activate test might be a path to really look into. Great work man!

**Comment by Scrivener07** [comment]
![screenshot141](https://user-images.githubusercontent.com/1912967/27888175-b018dcbc-61b2-11e7-9606-af55f78d977d.png)

**Comment by Scrivener07** [comment]
![screenshot142](https://user-images.githubusercontent.com/1912967/27888184-b9eaa36a-61b2-11e7-8e0c-b7b06cb71c8e.png)

**Comment by TheWhiteCollarPlayers** [comment]
Looks good, what is the Player field on the right side? Also, what is the kill count in the top left?

**Comment by TheWhiteCollarPlayers** [comment]
Per our discussion: in the future try to contact HUDFramework author and work on expansion of his framework to include show-hide other widget functionality

**Comment by TheWhiteCollarPlayers** [comment]
Per our discussion on voice: 
for changing turns: 
move a vault boy bobblehead around (maybe the Luck one?) so that it is in front of whoever's turn it is.
for views:
move the player so that their cards are at the bottom of the table and the camera is static behind those cards

**Comment by TheWhiteCollarPlayers** [comment]
Closing this issue as we have reached an agreement and solid working of how we want to display info to the player
