### ISSUE TITLE
AI will use a basic strategy in Blackjack

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#43]
Each blackjack game has a basic strategy, which is playing a hand of any total value against any dealer's up-card, which loses the least money to the house in the long term.

https://en.wikipedia.org/wiki/Blackjack#Basic_strategy
https://wizardofodds.com/games/blackjack/strategy/4-decks/

![blackjack basic strategy](https://user-images.githubusercontent.com/1912967/27773460-313cb70e-5f48-11e7-8de1-ce9cf08b789e.gif)

A second reference to go by depending on the rules.

![blackjack basic strategy - hits17](https://user-images.githubusercontent.com/1912967/27773478-9a79e9a8-5f48-11e7-8700-b92f459476be.gif)

**Comment by TheWhiteCollarPlayers** [comment]
That's a great plan, does this work with your personalities?

**Comment by Scrivener07** [comment]
Yes! The plan I have right now is to put basic strategy behavior into the default player so that all players use basic strategy by default. The personalities provide deviations from the default player behavior. 

Right now the AI will only consider the score of their own hand which deciding what to do. This issue aims to improve this at some point by having the AI also consider what the dealers up card is.

**Comment by TheWhiteCollarPlayers** [comment]
I am closing this issue as we have a set framework for the AI for blackjack at the moment and we did away with the different personalities, if you want to explore this again we can reopen it, but I am fine with the way we are approaching blackjack now.
