### ISSUE TITLE
Idea: Workaround for message boxes

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#44]
In vanilla Fo4, when you first start the game and are leaving Vault 111, items you pick up are automatically hotkeyed for you.... So, what about giving the player aid items when they are transported to the gambling cell, and assigning them to specific favorite item hotkeys, then using scripts attached to those aid items so that when the player presses the button, input is taken via that aid item press? For example: 1 = Hit, 2 = Stay, 3 = Increase Bet, 4 = Decrease Bet, etc.

**Comment by Scrivener07** [comment]
That is a great idea to look into. This vanilla user input has been kicking my ass.

**Comment by TheWhiteCollarPlayers** [comment]
One issue with the aid items which I have not thought about much is timing, for example you would want the items to only be valid at a certain time (during the player's turn), not quite sure how to work around that other than removing them and adding them back repeatedly

**Comment by TheWhiteCollarPlayers** [comment]
Are we set on pursuing the multiple activation text options? Can I close this issue?

**Comment by Scrivener07** [comment]
Here are some last thoughts on why we are closing this issue. 

Abusing a favorited inventory item for its hotkey and equip event is a bit too hacky compared to other options we can try at the moment. At this point even the multiple activation text method might not work out, but that is the direction I'm actively pursuing. 

I agree this issue can be closed.
