### ISSUE TITLE
HUD framework is still required for some HUD elements.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#50]
The rendering layer added by HUD framework is required for injected F4SE HUD elements to be visible on some areas of HUDMenu. That is also the reason why at least one hudwidget needs to be loaded in order to kickstart HUD Framework.

**Comment by Scrivener07** [comment]
![screenshot19](https://user-images.githubusercontent.com/1912967/34869852-526e99a0-f756-11e7-8a9b-b484534e7f57.png)

**Comment by TheWhiteCollarPlayers** [comment]
Are we in agreement that we intend to work the code so that HUDFramework is not required? Or are you planning on always having it as a requirement?

**Comment by Scrivener07** [comment]
This is possibly fixed with pull request #63

**Comment by Scrivener07** [comment]
Fixed and closed.
