### ISSUE TITLE
Wager cannot change with insufficient caps.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#52]
Values are not resetting correctly after a match.

### Problem 1
![screenshot4](https://user-images.githubusercontent.com/1912967/35485062-c1fd8794-0427-11e8-8853-76f22ea507e3.png)
In this screenshot the BET is stuck on 50 and cannot be changed except for setting MINIMUM to 5. On the last hand a bet of 50 was valid because there was sufficient CAPS. When a new match starts I need to check the players CAPS and reduce the last bet if they don't have the CAPS.

### Problem 2
![screenshot5](https://user-images.githubusercontent.com/1912967/35485164-665b0acc-0429-11e8-8b4f-cc4fb562d30f.png)
Its completely stuck here. I should also check that the player can at least afford the minimum bet. For example if the minimum bet is 5 caps and the player has 4 caps.

**Comment by TheWhiteCollarPlayers** [comment]
Are you going to keep the WagerMax option? I thought we had discussed on removing this as it wasn't really needed and so that the options all display fully

**Comment by Scrivener07** [comment]
There needs to be an upper limit to how much you can bet. At the moment the max bet is 50 caps. We discussed that we didnt need to make the WagerMax changeable. 

In any case the problem is not that a maximum wager exists. Its that values are not resetting correct after a match.

**Comment by Scrivener07** [comment]
I added some details to the OP.

**Comment by Scrivener07** [comment]
This is probably related to not fixing issue #49 correctly.

**Comment by Scrivener07** [comment]
* [Check the wager against the players bank, and reducing it to the minimum](https://github.com/Scrivener07/FO4_Games/blob/30f4a7c215a7617e41142a0fe67979a8d722e2b1/Data/Scripts/Source/FO4_Games/Games/Blackjack/Players/Human.psc#L101-L104)

**Comment by Scrivener07** [comment]
Fixed in pull request #88
