### ISSUE TITLE
HUDMenu has masked, drawable regions which add difficulty to adding UI elements.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#55]
The vanilla HUDMenu has masked, drawable regions which add difficulty to adding UI elements. If your custom UI element is not correctly configured for these special "visibility" regions they will cause your UI elements to become invisible or partially visible.

**Comment by TheWhiteCollarPlayers** [comment]
Is this something we need to work around? I'm not sure I understand fully why this is an issue...

**Comment by Scrivener07** [comment]
This causes invisible or partially visible hud elements. Sorry that I did not take the time to fill out the issue details.

**Comment by Scrivener07** [comment]
With pull request #63 this issue may be irrelevant now. As of F4SE v0.6.5 we can create/open standalone menus that are not affected by the HUD's region areas. This is what is being done in the pull request and the issue seems to be pending solved.

**Comment by Scrivener07** [comment]
Closing
