### ISSUE TITLE
To Do: Manually merge good stuff from Games_Vanilla into Games_WhiteCollar

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#58]
The games master does not include ANY implementation, magazine assets and records to be manually set on my end. Along with playing the game via the settlement object and more

**Comment by TheWhiteCollarPlayers** [comment]
All appropriate records are copied over to my current esp, all thats left is to rename them to remove the COPY000 that got added and to repoint the records.

**Comment by TheWhiteCollarPlayers** [comment]
This is done, everything works with just this plugin and the master, now the only ESP I will work out of is Games_WhiteCollar.esp
Closing issue

**Comment by Scrivener07** [comment]
Try to close issues only after the fix has been committed to a branch. If you can then also post a link to the commit that fixed an issue.

**Comment by TheWhiteCollarPlayers** [comment]
Reopening this until I commit the changes.

**Comment by TheWhiteCollarPlayers** [comment]
This is done with this commit:
Closing issue!
https://github.com/Scrivener07/FO4_Games/commit/4d4fe3e80e518c750c65826f2f38185d980b7e62
