### ISSUE TITLE
Wager a bet with caps, food, weapons, and ammo.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#6]
Currently a message box appears offering 5 static amounts to wager or a cancel option before a game starts. Even when an option is selected, no wager is actually placed at the start of the game or awarded when the game is over.

The options are as follows.
1. Cancel
2. 5
3. 10
4. 20
5. 50
6. 100

Before moving forward with completing this game element lets consider our options. 

On discord, we have previously discussed a barter themed approach to wagering a bet. Let me try to make a case for this idea. Fallouts world is a post apocalypse setting and also to some degree post society. I think one could also make the case that the world would also be post currency even though fallout lore uses caps as a primary currency. Even though [caps](http://fallout.gamepedia.com/Bottle_cap) are a part of lore I feel like they really dont make a good case for themselves to realistically work. 

Im not proposing to do away with caps or anything like that as we would still need a way to summarize what something is worth in numerical terms anyway. I mean to suggest we supplement the wagering process with a more realistic barter approach. I had the idea of not only being able to wager say 100 caps but also wager goods like ammo, food, water, weapons, and other valuables. I imagine that could work something like when its time to make your wager an inventory/container menu opens before the player and thats where they place items for their bets, including caps. This can be done because I can get the value of item with papyrus. 

Even if this is a good idea lets also consider the goals for our first milestone. If I had to estimate, I would say the development cost for something like a wagering system supplemented with bartering would be very low. On the other hand the full cost wont be fully realized until an attempt is made and we start to run into additional special edge cases for things we didnt consider up front. The benefit of going with a set of static options is that the development cost would be next to zero with no known special cases to consider.

Let me have it!

**Comment by TheWhiteCollarPlayers** [comment]
I do see great benefit in the static system from a development standpoint. However, I am a huge fan of the bartering system. Allow me to suggest one take on that system though (I accidentally mentioned this in the HUD issue): 

Prior to the player activating the blackjack table, they must talk to a "cashier" of sorts, could be any NPC, with whom they give the goods they wish to trade for "chips" (or something of the sort). The player doesn't actually receive anything back at this time, but rather the cashier keeps a balance of their "chips" which is the converted summed value of the goods they give up. That value is used as their "purse" after they start the game. Suppose then that the player ends the game with an amount still left in his "purse", the dealer would then give the player a "receipt" which the player would take back to the cashier and the receipt would be turned into caps which could be used to buy back the items that the player traded in. This way, we reduce the need of taking items into an inventory and converting them every time the player chooses to play again, so we reduce variability and we keep the great bartering system. The player is able to win extra caps through their receipt and buy back any items they want to and if they lose then they can only buy back the goods that they have enough credit on the receipt to do so.

I don't believe that this coding process would be very hard, but let me know what you think!

**Comment by TheWhiteCollarPlayers** [comment]
Do we still want to do this? In the current version it is just straight caps but we might be able to work out a system where the PC can barter items. Of course we could also just make the dealer NPC a vendor so that the PC could trade items with the dealer to get caps to play the games with.

**Comment by Scrivener07** [comment]
At this point a barter system is not within scope for the core of the games project. If you can work something out with an NPC vendor exchange as part of the vanilla standalone then go for it.

**Comment by Scrivener07** [comment]
Closing this. An attempt was made on branch `wager-item-bets` with commit 946843d
