### ISSUE TITLE
Document on the project wiki, Meet the gamblers.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#60]
These are the NPC that exist so far.

### Say hello to Harry!
- **Location:** Dugout Inn, Diamond City
![screenshot_154](https://user-images.githubusercontent.com/1912967/35467854-0cb9852c-02e2-11e8-8251-cc15d2ae663e.png)

### Say hello to Mr. Wallace!
- **Location:** Colonial Taphouse, Diamond City
![screenshot_152](https://user-images.githubusercontent.com/1912967/35467813-86b0e8a8-02e1-11e8-8386-c8265d358fa8.png)

### Say hello to Douglas!
- **Location:** Third Rail, Goodneighbor
![screenshot_153](https://user-images.githubusercontent.com/1912967/35467865-2a4c720c-02e2-11e8-87bf-b7393ad3ea76.png)

**Comment by Scrivener07** [comment]
Added some NPCs you mentioned in discord.

**Comment by TheWhiteCollarPlayers** [comment]
### **Say hello to Scribe Harrison!**

- **Location:** Mess Hall, Prydwen Airship
![harrison](https://user-images.githubusercontent.com/28495967/35629645-c1e24dc8-0664-11e8-91e8-2e5c38c3d1fb.png)

**Comment by TheWhiteCollarPlayers** [comment]
### **Say hello to Jackson!**

- **Location:** Diner, Vault 81
![jackson](https://user-images.githubusercontent.com/28495967/35629760-13969d18-0665-11e8-8126-aacc1c6da3c7.png)

**Comment by Scrivener07** [comment]
This is related to issue #19

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as I am merging it with issue #19
