### ISSUE TITLE
Commonwealth Implementation: To do

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#70]
-Fix note name issue [x]
-finish Blackjack table at settlement, make it so it requires a settler
-once all is said and done, thoroughly clean plugin, per Flen's report

**Comment by Scrivener07** [comment]
This issue is related to two others. Consider merging issue #19 and issue #60 here and then closing them.

**Comment by TheWhiteCollarPlayers** [comment]
Note name issue fixed with commit:
https://github.com/Scrivener07/FO4_Games/commit/a01a2a18b00151eb27a274b84c02691b63799e80
