### ISSUE TITLE
Add version check for F4SE

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#72]
In papyrus, add a version check on game reload in order to check that the scripts are present and of the correct version. Throw a big giant messagebox in the users face and prevent saving if the check fails.

**Comment by TheWhiteCollarPlayers** [comment]
I feel like you mentioned this, is this committed?

**Comment by Scrivener07** [comment]
No I havent started on this yet.

**Comment by Scrivener07** [comment]
A side note. The version check does not prevent saving if failure.

**Comment by TheWhiteCollarPlayers** [comment]
Should we close this? This appears to be working as expected in the current release of the mod.

**Comment by Scrivener07** [comment]
Yea, closed.
