### ISSUE TITLE
Blackjack camera positioning is wrong during some conditions.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#89]
The camera is twisted off center when started through dialogue with Mr. Wallace.
![377160_screenshots_20180308170922_1](https://user-images.githubusercontent.com/1912967/37183370-b61cae8c-2303-11e8-8f40-6bac42364ddb.jpg)

The camera is twisted off center when started through dialogue with Mr. Wallace.
![377160_screenshots_20180308173834_1](https://user-images.githubusercontent.com/1912967/37183372-b7e6c478-2303-11e8-94fb-517304c5ba2d.jpg)

It is even more off center when started through dialogue AND while sitting.
![377160_screenshots_20180308172851_1](https://user-images.githubusercontent.com/1912967/37183435-0c25c926-2304-11e8-9669-d5813c276d7e.jpg)

The camera also sometimes starts too far away!
![screenshot37](https://user-images.githubusercontent.com/1912967/37183448-1b49d244-2304-11e8-8000-ee8e618a950e.png)

The camera can start at different angles depending on what furniture you are seated in?
![377160_screenshots_20180308175040_1](https://user-images.githubusercontent.com/1912967/37183483-4994f458-2304-11e8-925c-c521a37fcc59.jpg)

**Comment by TheWhiteCollarPlayers** [comment]
This isn't unique to Mr. Wallace btw. This is something that occurs whenever you try to play the game while sitting, even at the settlement object (the activator not an NPC). Also the camera appearing far away is not unique to Mr. Wallace either, it has happened to me a few times but I have never been able to consistently replicate it. From my testing, 9/10 the camera works fine if you just stand still while going through the dialogue or activating the table

**Comment by Scrivener07** [comment]
This is possibly solved with commit 6c0c4f1, awaiting a play test by the original reporter of the bug.

**Comment by Scrivener07** [comment]
Fixed with commit 6c0c4f1
