### ISSUE TITLE
Simple AI for dealer and opponent players.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#9]
Compete against the dealer and opponent players in blackjack.

At this point the competitor AI is fully functional. The issue is that for every game the maximum amount of competitors will be allocated for each game. Instead the amount of competitors should be variable. The amount of competitors should be determined by how many NPC actors are seated around the in world table before a game starts. I was thinking I could make a custom stool to place around tables and the game will allocate a competitor for each chair that has an NPC sitting in it.

**Comment by TheWhiteCollarPlayers** [comment]
That sounds like a great idea! I have been practicing with idle markers and animations, so that would certainly be doable, do you have a plan for checking to see if a chair has an NPC in it?

**Comment by Scrivener07** [comment]
Renamed the issue and removed the enhancement tag. Im rescoping the issue to the entire top level feature of competitors in general.

**Comment by Scrivener07** [comment]
I added this issue to the playable milestone. We need the competitors feature for this milestone because the dealer is technically a competitor.

**Comment by Scrivener07** [comment]
Ive brought up AI personalities in issue #18 as a future possibility.

**Comment by TheWhiteCollarPlayers** [comment]
Should this issue be closed since we have issue #18 ?

**Comment by Scrivener07** [comment]
Nah, these issues sound really similar but the simple AI ([Player](https://github.com/Scrivener07/FO4_Gambling/blob/eac26ef6b5d6717e6d1e346f01189d424138c34c/Data/Scripts/Source/FO4_Gambling/Gambling/BlackJack/Player.psc)) and their [personalities](https://github.com/Scrivener07/FO4_Gambling/tree/eac26ef6b5d6717e6d1e346f01189d424138c34c/Data/Scripts/Source/FO4_Gambling/Gambling/BlackJack/Players) will coexist at the same time.

A personality extends the `Player` giving it all the behaviors of the simple `Player` AI through inheritance. An empty personality script would behave exactly like a generic, simple player. A personality defines what makes each player different from one another expressed by behaviors. This is why the personality scripts are so short. They literally only define the differences and additions to the simple player AI.

**Comment by TheWhiteCollarPlayers** [comment]
Ah, I see, thanks for clarifying

**Comment by Scrivener07** [comment]
Closing this as blackjack has a simple and playable AI at this point.
