### ISSUE TITLE
NPC dialogue audio is missing.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#91]
NPC dialogue to start a mini-game is painfully long. This occurs because there is no audio recorded yet, it'll get fixed once voiced dialogue audio is implemented.

**Comment by TheWhiteCollarPlayers** [comment]
Voice lines round 1:
https://www.dropbox.com/sh/tkx2vqk0lg5odg8/AADdW1kV4t4wM895BCdrtgrJa?dl=0

**Comment by TheWhiteCollarPlayers** [comment]
Closing this, I am opening a new issue to mark as a to do list for voice implementation
