### ISSUE TITLE
The dealer should peek at their hole card for a blackjack.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#98]
Here the dealer has a higher value hand than the player but the game is scored as a push, instead of a lose. We should research the rules of Blackjack to see exactly how this should be scored. Maybe its okay the way it is though I think if the hands were switched around the game would be scored as a Blackjack.
![screenshot60](https://user-images.githubusercontent.com/1912967/37215370-c1212178-2385-11e8-9e03-a7be6b845acb.png)

**Comment by Scrivener07** [comment]
Ill leave this up as a non-bug until I have sources and citations.

**Comment by TheWhiteCollarPlayers** [comment]
I am fine with leaving it as a push, different sites site different rules depending on the type of play. In "Casino" play the rule is a natural 21 (blackjack) beats a non-natural 21
This quote comes from the website of a popular card deck manufacturer:
"If a player's first two cards are an ace and a "ten-card" (a picture card or 10), giving him a count of 21 in two cards, this is a natural or "blackjack." If any player has a natural and the dealer does not, the dealer immediately pays that player one and a half times the amount of his bet. If the dealer has a natural, he immediately collects the bets of all players who do not have naturals, (but no additional amount). If the dealer and another player both have naturals, the bet of that player is a stand-off (a tie), and the player takes back his chips.

If the dealer's face-up card is a ten-card or an ace, he looks at his face-down card to see if the two cards make a natural. If the face-up card is not a ten-card or an ace, he does not look at the face-down card until it is the dealer's turn to play."

Source: https://www.bicyclecards.com/how-to-play/blackjack/

**Comment by TheWhiteCollarPlayers** [comment]
My vote is to go with whatever method was used in Fallout: New Vegas for this question

**Comment by Scrivener07** [comment]
http://fallout.wikia.com/wiki/Blackjack
> **Blackjack Payout**
> A blackjack is a hand that is an Ace and a 10-point card (it is special since it is a 21 with only two cards). If the dealer gets a blackjack, the player's second card will be revealed to determine if the player also has blackjack. If not, the player instantly loses, without any opportunity to play. If the player gets a blackjack and the dealer does not, the player instantly wins and gets a bonus payout based on the casino. A blackjack payout of 3 to 2 means the player gets back 3 chips for 2 chip they wagered. If both the dealer and the player get blackjack, it is a push and the player keeps his bet.

The question I was asking in the original issue was flawed because my blackjack dealer does not peek at their hand before the player plays their hand. If I make my dealer peek at their hand for a natural 21 then the only other hand that could push that would also be a natural 21.

**Comment by TheWhiteCollarPlayers** [comment]
I like this method the best, would you want to pursue this?

**Comment by Scrivener07** [comment]
Yes. It should improve the overall feel of the game too in my opinion.

**Comment by Scrivener07** [comment]
Fixed with pull request #120, closing this.
