### ISSUE TITLE
Sim Settlements Industrial Revolution Conflicts with Magazine location

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Games#99]
The location of the magazine conflicts with sim settlements (or its addon industrial revolution can't remember which) as it adds a beer and recipe to the same spot.
Just so you know

**Comment by Scrivener07** [comment]
Heres a screenshot of the original too.
![userreport](https://user-images.githubusercontent.com/1912967/37222289-82bc2300-239a-11e8-8487-4ae87cc25ced.PNG)

**Comment by TheWhiteCollarPlayers** [comment]
Moved perk magazine to ``BeaconHillPub``, confirmed compatible with Sim Settlements and its expansions by kinggath himself and my own playtesting.
https://github.com/Scrivener07/FO4_Games/commit/5bdd898149b27da925bf59359ef63dc0240ca1ef

**Comment by Scrivener07** [comment]
Excellent.
